#!/usr/bin/env perl
# Copyright (C) 2018–2021  Alex Schroeder <alex@gnu.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

=head1 NAME

face-generator - a web app to combine random images into faces

=head1 DESCRIPTION

This command starts a web server using Mojolicious.

In addition to the usual Mojolicious commands, this application also implements
the C<random> command using L<Game::FaceGenerator::Command::random>.

=head1 SEE ALSO

For more information, see L<Game::FaceGenerator> and
L<Game::FaceGenerator::Command::random>, and L<Mojolicious>.

=head1 LICENSE

GNU Affero General Public License

=cut

use FindBin;
use lib "$FindBin::Bin/../lib";
my $res = require Game::FaceGenerator
    or not defined $res and die "Cannot load Game::FaceGenerator: $!"
    or not $res and die "Game::FaceGenerator did not return a true value\n";
